import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
      <ul>
        <li>Home</li>
        <li>About</li>
        <li>Blog</li>
        <li>Contact</li>
      </ul>
      </nav>      
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className='styles.title'>learning NextJs</h1>
        <p>
          Get started by editing
        </p>
        <div className="blogs">
          <h2>Popular Blogs</h2>
        <div className="blogItem">
            <h3>
              Let's Start learning NextJs
            </h3>
            <p>
              Get started by editing
            </p>
          </div>
          <div className="blogItem">
            <h3>
              Let's Start learning NextJs
            </h3>
            <p>
              Get started by editing
            </p>
          </div>
          <div className="blogItem">
            <h3>
              Let's Start learning NextJs
            </h3>
            <p>
              Get started by editing
            </p>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>
      </main>
    </>
  )
}
